name: Enviar mensaje en pull_request
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Enviar mensaje
      run: |
        echo "Se ha hecho un pull a la rama ${{ github.ref }} por el usuario ${{ github.actor }} "
