name: Update Commits Count

on:
  push:
    branches:
      - '**'

jobs:
  update-commits:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Count commits per contributor
      run: |
        git shortlog -s -n > commits.txt

    - name: Commit and push changes
      run: |
        git config --global user.name 'JabelResendiz'
        git config --global user.email 'jabelresendiz18@gmail.com'
        git add commits.txt
        git commit -m 'Update commits count'
        git push

